# Worlds used for some abilities
worlds:
  # Overworld dimension
  world: "world"
  # Nether dimension
  world_nether: "world_nether"
  # End dimension
  world_the_end: "world_the_end"

# The /origin swap command, allowing players to switch origin at will
swap-command:
  # Enable the swap command
  enabled: true
  # Permission required for origin swap command
  permission: originsreborn.admin
  # Reset player data like inventory and spawn point when switching origins using the /origin swap command
  reset-player: false
  # Charge players using Vault to switch their origins
  vault:
    # Enable charging players with Vault
    enabled: false
    # Permission to bypass the cost of the swap command
    bypass-permission: originsreborn.costbypass
    # Cost of switching origin
    cost: 1000
    # Currency symbol for the economy
    currency-symbol: "$"

# Settings for origin selection
origin-selection:
  # Randomise origins instead of letting players pick
  randomise: false
  # Allows players to choose a new origin when they die
  # If randomise is enabled this will reroll their origin to something random
  death-origin-change: false
  # Amount to scroll per scroll button click
  scroll-amount: 1
  # Allows the player to pick a 'Random' option
  random-option:
    # Enable the random option choice - does nothing if randomise is enabled
    enabled: true
    # Origins to exclude from random options
    exclude:
      - human

# Settings for the Orb of Origin
orb-of-origin:
  # Reset player data like inventory and spawn point when switching origins using the Orb of Origin
  reset-player: false
  # Consume the Orb of Origin upon use
  consume: true
  # Enable recipe for crafting the Orb of Origin
  enable-recipe: false
  # Crafting recipe for the Orb of Origin
  recipe:
    - [minecraft:air, minecraft:diamond, minecraft:air]
    - [minecraft:diamond, minecraft:nether_star, minecraft:diamond]
    - [minecraft:air, minecraft:diamond, minecraft:air]

# Settings for the resource pack
# You can change this to merge with other packs or disable it to put the pack elsewhere.
resource-pack:
  # Whether to enable the resource pack
  # If this is set to false you should send the pack to players either in server.properties or in another plugin
  enabled: true
  # Link to the pack
  # This can be changed, but it should always contain the files in the original pack for the GUI
  link: "https://github.com/cometcake575/Origins-Reborn/raw/main/src/main/Origins%20Pack.zip"

# Miscellaneous display options
display:
  # Enable prefixes in tab and on display names with the names of origins
  enable-prefixes: false
  # Language file to use - default is en_us
  language: en_us

# Restrictions placed on origin selection
# These are designed for use with addon plugins that add many new origins
# If you run out of origins that fit the restrictions you may experience issues
restrictions:
  # Rule for reusing origins
  # "NONE" allows origins to be reused
  # "PERPLAYER" means individual players can only use an origin once
  # "ALL" means no players can use an origin again after one has selected it
  reusing-origins: "NONE"
  # Prevent players from having the same origins as other players
  # This is locked on if reusing-origins is set to ALL
  prevent-same-origins: false

# Config version - do not touch this!
config-version: 2.2.0
