name: Origins-Reborn
version: 2.1.3
main: com.starshootercity.OriginsReborn
description: Paper plugin inspired by the Origins mod by Apace
api-version: '1.20'
author: cometcake575

softdepend:
  - Geyser-Spigot

permissions:
  originsreborn.default:
    default: true
    description: Default permissions for Origins-Reborn
  originsreborn.costbypass:
    default: false
    description: Bypass cost of origin swapping
  originsreborn.admin:
    default: op
    description: Use admin commands for Origins-Reborn

commands:
  origin:
    permission: originsreborn.default
    description: Modify origins
    usage: /<command>
